GPIO: gpio-pxa: fix building without CONFIG_OF
Patch 7212157267 "GPIO: gpio-pxa: fix devicetree functions" added an
"xlate" function pointer to the irq_domain_ops, but this function
is nor declared or defined anywhere when CONFIG_OF is disabled, causing
the build error:

drivers/gpio/gpio-pxa.c:532:11: error: 'irq_domain_xlate_twocell' undeclared here (not in a function)

Extending the DT-only code section to cover the irq_domain_ops
and the pxa_gpio_dt_ids solves this problem and makes it clearer
which code is actually used without DT.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Linus Walleij <linus.walleij@linaro.org>