dt-bindings: bus: fix STM32 System Bus
Fix 'make dt_binding_check' that shows some errors due to missing headers.

Error: Documentation/devicetree/bindings/bus/
st,sys-bus.example.dts:41.29-30 syntax error
FATAL ERROR: Unable to parse input tree

Signed-off-by: Fabrice Gasnier <fabrice.gasnier@foss.st.com>
Change-Id: I8c01984967b3c6cabbaa811c6cbc67b648b88f6b
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/linux-stm32/+/312993
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>
Reviewed-by: Gatien CHEVALLIER <gatien.chevallier@st.com>
Reviewed-by: Yann GAUTIER <yann.gautier@foss.st.com>
Domain-Review: Yann GAUTIER <yann.gautier@foss.st.com>