ASoC: fsl-ssi: fix build breakage introduced by commit 180ba0d3d731 ARM: i.MX: Compile FIQ code for AVIC & TZIC only
The commit 180ba0d3d731 "ARM: i.MX: Compile FIQ code for AVIC & TZIC only"
disables the build of the file containing the mxc_set_irq_fiq()
function for configurations that do enable CONFIG_MXC_TZIC or
CONFIG_MXC_AVIC, leading to the following build error when compiling
sound/soc/fsl/ for e.g. i.MX6 (unless any machine that defines either
symbol is selected too):
    sound/built-in.o: In function `imx_pcm_fiq_free':
    last.c:(.text+0x2aca8): undefined reference to `mxc_set_irq_fiq'
    sound/built-in.o: In function `imx_pcm_fiq_init':
    last.c:(.text+0x2b1a4): undefined reference to `mxc_set_irq_fiq'
    last.c:(.text+0x2b200): undefined reference to `mxc_set_irq_fiq'
    make[1]: *** [vmlinux] Error 1
    make: *** [sub-make] Error 2