watchdog: it8712f_wdt.c: fix includes
Fix build errors by adding missing header file:

drivers/watchdog/it8712f_wdt.c:127: error: implicit declaration of function 'request_muxed_region'
drivers/watchdog/it8712f_wdt.c:141: error: implicit declaration of function 'release_region'
drivers/watchdog/it8712f_wdt.c:412: error: implicit declaration of function 'request_region'

Signed-off-by: Randy Dunlap <rdunlap@xenotime.net>
Signed-off-by: Wim Van Sebroeck <wim@iguana.be>