drivers: base.h implicitly depends on <linux/notifier.h>
This file is currently relying on <linux/module.h> sneaking it in
through the twisted include paths from device.h.  Once that
is cleaned up, this will happen:

In file included from drivers/base/init.c:12:
drivers/base/base.h:34: error: field ‘bus_notifier’ has incomplete type
make[3]: *** [drivers/base/init.o] Error 1

Fix it up in advance, so the cleanup can continue.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>