dt-bindings: interrupt-controller: stm32-exti: fix irq nexus child node
Fix 'make dt_binding_check' that shows some errors due to missing GIC
header:

Error: Documentation/devicetree/bindings/interrupt-controller/
 st,stm32-exti.example.dts:44.32-33 syntax error
FATAL ERROR: Unable to parse input tree

Signed-off-by: Fabrice Gasnier <fabrice.gasnier@foss.st.com>
Change-Id: Ia1a2ceea24c9d18273ab7ef91d949185e2ee2296
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/linux-stm32/+/312989
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>
Reviewed-by: Antonio Maria BORNEO <antonio.borneo@foss.st.com>
Reviewed-by: Amelie DELAUNAY <amelie.delaunay@foss.st.com>
Domain-Review: Amelie DELAUNAY <amelie.delaunay@foss.st.com>