ARM: imx: select ARM_CPU_SUSPEND if necessary
As tests using 'make randconfig' showed, imx5 requires the same logic
as imx6 to select ARM_CPU_SUSPEND when building with power management
enabled.

The defconfig does not have this problem because it enables imx6
as well, but disabling it leads to this warning:

arch/arm/mach-imx/built-in.o: In function `v7_cpu_resume':
arch/arm/mach-imx/head-v7.S:104: undefined reference to `cpu_resume'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Sascha Hauer <kernel@pengutronix.de>
Cc: Shawn Guo <shawn.guo@linaro.org>