arm fix implicit asm/vga.h use in mach-orion5x/pci.c
So that we don't get this:

arch/arm/mach-orion5x/pci.c: In function 'orion5x_pci_sys_setup':
arch/arm/mach-orion5x/pci.c:563: error: 'vga_base' undeclared (first use in this function)
arch/arm/mach-orion5x/pci.c:563: error: (Each undeclared identifier is reported only once
arch/arm/mach-orion5x/pci.c:563: error: for each function it appears in.)
make[3]: *** [arch/arm/mach-orion5x/pci.o] Error 1

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>