mm-introduce-a-common-interface-for-balloon-pages-mobility-fix-fix-fix
Fixes build failure from "mm: introduce a common interface for balloon
pages mobility":

mm/balloon_compaction.c: In function 'balloon_page_putback':
mm/balloon_compaction.c:243: error: implicit declaration of function '__WARN'

Generic code calls WARN_ON(), not __WARN() directly.

Signed-off-by: David Rientjes <rientjes@google.com>
Cc: Rafael Aquini <aquini@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>