mips: fix typo introduced by resource handling cleanup
Commit 28f65c11f2ffb3957259dece647a24f8ad2e241b accidentally turned "rc"
into "rcrc" which causes this compile error:

arch/mips/pci/pci-rc32434.c: In function 'rc32434_pci_init':
arch/mips/pci/pci-rc32434.c:218: error: 'rcrc32434_res_pci_io1' undeclared (first use in this function)

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
CC: Joe Perches <joe@perches.com>