mm, arch: fix two errors in calling mem_init_print_info()
Fix two errors in calling mem_init_print_info() caused by incidents.

All error/warnings:

   arch/microblaze/mm/init.c: In function 'mem_init':
>> arch/microblaze/mm/init.c:249:22: error: 'str' undeclared (first use in this function)
   arch/microblaze/mm/init.c:249:22: note: each undeclared identifier is reported only once for each function it appears in

vim +/str +249 arch/microblaze/mm/init.c

   243		/* this will put all memory onto the freelists */
   244		free_all_bootmem();
   245	#ifdef CONFIG_HIGHMEM
   246		highmem_setup();
   247	#endif
   248
 > 249		mem_init_print_info(str);
   250	#ifdef CONFIG_MMU
   251		pr_info("Kernel virtual memory layout:\n");
   252		pr_info("  * 0x%08lx..0x%08lx  : fixmap\n", FIXADDR_START, FIXADDR_TOP);

Signed-off-by: Jiang Liu <jiang.liu@huawei.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>