drivers/thermal/exynos_thermal.c: fix build error
Fix the following error:
drivers/thermal/exynos_thermal.c:393:4: error: too few arguments to function
`thermal_zone_device_register'

Add the missing 'mask' argument.

Signed-off-by: Sachin Kamat <sachin.kamat@linaro.org>
Signed-off-by: Sachin Kamat <sachin.kamat@samsung.com>
Cc: Guenter Roeck <guenter.roeck@ericsson.com>
Cc: Len Brown <lenb@kernel.org>
Cc: "Brown, Len" <len.brown@intel.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>