ARM: bpf_jit: seccomp filtering: fixup merge conflict
Commit e4c67f4c0479d8e3cb0 (ARM: net: bpf_jit: make code generation less
dependent on struct sk_filter.) caused a merge conflict with commit
79617801ea0c0e6 (filter: bpf_jit_comp: refactor and unify BPF JIT image
dump output) resulting in a build failure:

arch/arm/net/bpf_jit_32.c: In function '__bpf_jit_compile':
arch/arm/net/bpf_jit_32.c:930:16: error: 'fp' undeclared (first use in this function)
    bpf_jit_dump(fp->len, alloc_size, 2, ctx.target);

Fix this up by using ctx.prog_len that is being set before we enter
__bpf_jit_compile().

Signed-off-by: Daniel Borkmann <dborkman@redhat.com>
Reported-by: Arnd Bergmann <arnd@arndb.de>
Cc: Nicolas Schichan <nschichan@freebox.fr>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>